STIFI-61 TTS echo route
SDiFI/headless pull request #3
Opened 2023-07-28 11:26 UTC by SmariF89

This modifies the echo route so that it will _audibly_ echo caller's speech using TTS.
Before it only echoed the caller by logging what he said in console.

With the conclusion of this implementation we have set up a nice base for a continued implementation of an IVR-client for SDiFI with a continuous flow of user speech and TTS responses in their respective directions.

2023-07-28 12:38 UTC, SmariF89 commented
@rkjaran Klára e.t.v. að fara yfir og tvinna https://github.com/SDiFI/headless/pull/2 og endurgrunna svo þessa við master.

2023-07-28 13:51 UTC, rkjaran requested changes
Smá nitpick.

2023-07-28 13:51 UTC, rkjaran commented on src/app.py
> +            current_app.logger.exception("Something went wrong while receiving data.")
re`raise`a

2023-07-28 13:51 UTC, rkjaran commented on src/app.py
> +            )
re`raise`a

2023-07-31 10:32 UTC, SmariF89 commented on src/app.py
> +            current_app.logger.exception("Something went wrong while receiving data.")
Græjað.

2023-07-31 12:23 UTC, merged